var permissionsByRole = {
    'view_courses': ['student', 'employee', 'professor', 'administrator'],
    'add_course': ['professor', 'academic organization', 'administrator'],
    'edit_course': ['professor', 'academic organization', 'administrator'],
    'delete_course': ['professor', 'academic organization', 'administrator'],
    'view_jobs': ['student', 'employee', 'recruiter', 'recruitment organisation', 'administrator'],
    'add_job_post': ['recruiter', 'recruitment organisation', 'administrator'],
    'edit_job_post': ['recruiter', 'recruitment organisation', 'administrator'],
    'delete_job_post': ['recruiter', 'recruitment organisation', 'administrator'],
    'view_profiles': ['professor', 'recruiter', 'academic organization', 'recruitment organisation', 'administrator'],
    'add_profile': ['administrator'],
    'view_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'edit_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'delete_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'view_other_profile': ['professor', 'recruiter', 'academic organization', 'recruitment organisation', 'job seeker', 'administrator'],
    'edit_other_profile': ['administrator'],
    'delete_other_profile': ['administrator'],
    'view_recruitment': ['recruiter', 'recruitment organisation', 'administrator'],
    'access_MCDSS': ['student', 'employee', 'professor', 'administrator'],
    'view_skills': ['student', 'employee', 'professor', 'administrator'],
    'upload_own_avatar': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'get_own_avatar': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'examine_appliant_profile': ['recruiter', 'administrator'],
    'examine_student_profile': ['professor', 'academic organization', 'administrator'],
    'examine_professor_profile': ['academic organization', 'administrator'],
    'examine_employee_profile': ['recruitment organization', 'administrator'],
    'view_employee_long_term_career_path': ['recruitment organization', 'administrator'],
    'upload_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'retrieve_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'delete_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'manage_own_notifications': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'manage_own_notifications_preferences': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker', 'administrator'],
    'create_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'update_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'delete_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'get_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'get_other_cv': ['professor', 'recruiter', 'job seeker', 'administrator'],
    'get_their_job_applications': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'select_desired_job_locations': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'search_for_available_job_postings': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'employee', 'job seeker', 'administrator'],
    'apply_for_a_job_position': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'get_job_recommendations': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker', 'administrator'],
    'manage_applications_for_created_job_postings': ['recruiter', 'recruitment organisation', 'administrator'],
    'get_recruitment_recommendations': ['recruiter', 'administrator']
}

export default permissionsByRole;