var permissionsByRole = {
    'view_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'edit_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'delete_own_profile': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'upload_own_avatar': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'get_own_avatar': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'examine_appliant_profile': ['recruiter'],
    'examine_student_profile': ['professor', 'academic organization'],
    'examine_professor_profile': ['academic organization'],
    'examine_employee_profile': ['recruitment organization'],
    'view_employee_long_term_career_path': ['recruitment organization'],
    'upload_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'retrieve_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'delete_own_files': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'manage_own_notifications': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'manage_own_notifications_preferences': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'recruitment organisation', 'employee', 'job seeker'],
    'create_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'update_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'delete_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'get_own_cv': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'get_other_cv': ['professor', 'recruiter', 'job seeker'],
    'get_their_job_applications': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'select_desired_job_locations': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'search_for_available_job_postings': ['student', 'professor', 'recruiter', 'life long learner', 'academic organization', 'employee', 'job seeker'],
    'apply_for_a_job_position': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'get_job_recommendations': ['student', 'professor', 'recruiter', 'life long learner', 'employee', 'job seeker'],
    'create_job_post': ['recruiter'],
    'update_job_post': ['recruiter'],
    'delete_job_post': ['recruiter'],
    'manage_applications_for_created_job_postings': ['recruiter', 'recruitment organisation'],
    'get_recruitment_recommendations': ['recruiter']
}

export default permissionsByRole;