export const environment = {
  production: true,
  localStorageSecretKey: 'QC_secret_key_to_be_replaced',
  recomendationsUrl : 'http://qualichain.epu.ntua.gr:5000/recommendations',
  recomendationsUrlByCV : 'http://qualichain.epu.ntua.gr:7000/recommend',
  coursesUrl: 'http://qualichain.epu.ntua.gr:5004/courses',
  uploadFilesUrl : 'http://qualichain.epu.ntua.gr:5004/user',
  downloadFilesUrl : 'http://qualichain.epu.ntua.gr:5004/download',
  deleteFilesUrl : 'http://qualichain.epu.ntua.gr:5004/delete',
  badgesUrl : 'http://qualichain.epu.ntua.gr:5000/badges',
  authUrl : 'http://qualichain.epu.ntua.gr:5004/auth',
  IAMtokenvalidation : false,
  IAMAuthUrl : 'https://qualichain.herokuapp.com/users',
  IAMValidateTokenUrl : 'https://qualichain.herokuapp.com/auth/validateToken',
  usersUrl : 'http://qualichain.epu.ntua.gr:5004/users',
  userUrl : 'http://qualichain.epu.ntua.gr:5004/user',
  jobsUrl : 'http://knowledgebizvpn.ddns.net:8000/jobs',
  jobsProfilesUrl : 'http://knowledgebizvpn.ddns.net:8000/profiles',
  skillsUrl : 'http://qualichain.epu.ntua.gr:5004/skills',
  specializationsURL : 'http://qualichain.epu.ntua.gr:5004/specializations',
  notificationsURL : 'http://qualichain.epu.ntua.gr:5004/notifications',
  cvUrl : 'http://knowledgebizvpn.ddns.net:8000/cv',//'http://qualichain.epu.ntua.gr:5000/CV',
  skillsCV : 'http://knowledgebizvpn.ddns.net:8000/skills',
  jobmatchingUrl : 'http://knowledgebizvpn.ddns.net:8000/jobs',//'http://localhost:8000/jobs',
  jobpostUrl : 'http://knowledgebizvpn.ddns.net:8000/jobs',
  validateCertificate : 'https://qualichain.herokuapp.com/qualichain/validateCertificate',
  JwtModule: {
    allowedDomains: ['localhost','qualichain.epu.ntua.gr', 'qualichain.herokuapp.com', 'fenix.tecnico.ulisboa.pt/oauth'],
    disallowedRoutes: ["http://example.com/examplebadroute/"]
  },
  CVRecomendationUrl: 'http://qualichain.epu.ntua.gr:8080/curriculum_recommendation',
  mcdssURL: 'http://qualichain.epu.ntua.gr:7070/mcdss',
  uploadUserAvatar: 'http://qualichain.epu.ntua.gr:5004/upload',
  selectUrl: 'http://qualichain.epu.ntua.gr:5004/select',
  notificationPreferences: 'http://qualichain.epu.ntua.gr:5004/set',
  visualiserUrl: 'http://qualichain.epu.ntua.gr:8000/visualiser',
  //uploadCVToKG: 'https://demo.iais.fraunhofer.de/dobie',
  uploadCVToKG: '/dobie',
  insertTextTriples: 'http://knowledgebizvpn.ddns.net:8000/insertTextTriples',
  permissionsUrl: 'http://qualichain.epu.ntua.gr:5004/user_permissions',
  avatarURL: 'http://qualichain.epu.ntua.gr:5004/get',
  thesisURL: 'http://qualichain.epu.ntua.gr:5004/thesis',
  questionnaireURL: 'http://qualichain.epu.ntua.gr:5004/questionnaire'
};
